name: Taki Stream DZ 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ffmpeg curl jq fontconfig fonts-dejavu-core imagemagick
          mkdir -p ~/.fonts
          curl -L "https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf" \
            -o ~/.fonts/NotoColorEmoji.ttf
          fc-cache -f -v

      - name: Run Stream
        env:
          YOUTUBE_STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
          LOGO_URL: ${{ secrets.LOGO_URL }}
        run: bash stream.sh
